spring:
  application:
    name: spu
  profiles:
    active: dev
  cloud:
    config:
      enabled: true
      import-check.enabled: false
      uri: http://localhost:8888 # Replace with your Config Server URI

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
